/**
 * This file was generated by flotiq-api-typegen command
 * Generated at: 2026-08-07T06:48:03.648Z
 */

import {
  DataLink,
  ApiRequest,
  BaseObject,
  SearchParams,
  HydratedSearchResponse,
  InternalGeneratedFormsBase,
  InternalGeneratedForms,
  InternalGeneratedFormsHydrated,
  InternalGeneratedFormsHydratedTwice,
  InternalMediaBase,
  InternalMedia,
  InternalMediaHydrated,
  InternalMediaHydratedTwice,
  InternalPluginSettingsBase,
  InternalPluginSettings,
  InternalPluginSettingsHydrated,
  InternalPluginSettingsHydratedTwice,
  InternalTagBase,
  InternalTag,
  InternalTagHydrated,
  InternalTagHydratedTwice,
  InternalWebhooksBase,
  InternalWebhooks,
  InternalWebhooksHydrated,
  InternalWebhooksHydratedTwice,
} from "@flotiq/flotiq-api-sdk";

type StringWithAutocomplete<T> = T | (string & Record<never, never>);

declare module "@flotiq/flotiq-api-sdk" {
  export type AnySpaceCTD =
    | Recipe
    | InternalGeneratedForms
    | InternalMedia
    | InternalPluginSettings
    | InternalTag
    | InternalWebhooks;

  export type AnySpaceCTDHydrated =
    | RecipeHydrated
    | InternalGeneratedFormsHydrated
    | InternalMediaHydrated
    | InternalPluginSettingsHydrated
    | InternalTagHydrated
    | InternalWebhooksHydrated;

  export type AnySpaceCTDHydratedTwice =
    | RecipeHydratedTwice
    | InternalGeneratedFormsHydratedTwice
    | InternalMediaHydratedTwice
    | InternalPluginSettingsHydratedTwice
    | InternalTagHydratedTwice
    | InternalWebhooksHydratedTwice;

  export type AnySpaceCTDBase =
    | RecipeBase
    | InternalGeneratedFormsBase
    | InternalMediaBase
    | InternalPluginSettingsBase
    | InternalTagBase
    | InternalWebhooksBase;

  // #region recipe

  export interface RecipeBase extends BaseObject<"recipe"> {
    name: string;

    /**
     * Slug can only have alphanumerical characters, - and _
     */
    slug: string;
    image?:
      | Array<DataLink>
      | Array<InternalMedia>
      | Array<InternalMediaHydrated>
      | Array<InternalMediaHydratedTwice>
      | Array<InternalMediaBase>;
    description?: string;
    ingredients?: Array<Recipe.IngredientsBase>;
    steps?: Array<Recipe.StepsBase>;
    cookingTime?: string;
    servings?: number;
  }

  export interface Recipe extends RecipeBase {
    image?: Array<DataLink>;
    ingredients?: Array<Recipe.Ingredients>;
    steps?: Array<Recipe.Steps>;
  }

  export interface RecipeHydrated extends RecipeBase {
    image?: Array<InternalMedia>;
    ingredients?: Array<Recipe.IngredientsHydrated>;
    steps?: Array<Recipe.StepsHydrated>;
  }

  export interface RecipeHydratedTwice extends RecipeBase {
    image?: Array<InternalMediaHydrated>;
    ingredients?: Array<Recipe.IngredientsHydratedTwice>;
    steps?: Array<Recipe.StepsHydratedTwice>;
  }

  export namespace Recipe {
    export type FilterableFields = StringWithAutocomplete<
      | "name"
      | "slug"
      | "image"
      | "image[*].type"
      | "image[*].dataUrl"
      | "description"
      | "ingredients"
      | "steps"
      | "cookingTime"
      | "servings"
      | "ingredients[*].amount"
      | "ingredients[*].unit"
      | "ingredients[*].product"
      | "steps[*].image"
      | "steps[*].image[*].type"
      | "steps[*].image[*].dataUrl"
      | "steps[*].step"
    >;

    // #region Recipe.ingredients

    export interface IngredientsBase {
      amount?: number;
      unit?:
        | ""
        | "g"
        | "kg"
        | "ml"
        | "pcs"
        | "tablespoon"
        | "teaspoon"
        | "ounce"
        | "pound"
        | "cup"
        | "clove"
        | "pinch";
      product?: string;
    }

    export interface Ingredients extends IngredientsBase {}

    export interface IngredientsHydrated extends IngredientsBase {}

    export interface IngredientsHydratedTwice extends IngredientsBase {}

    export namespace Ingredients {
      export type FilterableFields = StringWithAutocomplete<
        "amount" | "unit" | "product"
      >;
    }

    // #endregion

    // #region Recipe.steps

    export interface StepsBase {
      image?:
        | Array<DataLink>
        | Array<InternalMedia>
        | Array<InternalMediaHydrated>
        | Array<InternalMediaHydratedTwice>
        | Array<InternalMediaBase>;
      step?: string;
    }

    export interface Steps extends StepsBase {
      image?: Array<DataLink>;
    }

    export interface StepsHydrated extends StepsBase {
      image?: Array<InternalMedia>;
    }

    export interface StepsHydratedTwice extends StepsBase {
      image?: Array<InternalMediaHydrated>;
    }

    export namespace Steps {
      export type FilterableFields = StringWithAutocomplete<
        "image" | "image[*].type" | "image[*].dataUrl" | "step"
      >;
    }

    // #endregion
  }

  // #endregion

  export interface FlotiqObjectAPI {
    recipe: ApiRequest<
      Recipe,
      RecipeHydrated,
      RecipeHydratedTwice,
      Recipe.FilterableFields
    >;

    _generated_forms: ApiRequest<
      InternalGeneratedForms,
      InternalGeneratedFormsHydrated,
      InternalGeneratedFormsHydratedTwice,
      InternalGeneratedForms.FilterableFields
    >;

    _media: ApiRequest<
      InternalMedia,
      InternalMediaHydrated,
      InternalMediaHydratedTwice,
      InternalMedia.FilterableFields
    >;

    _plugin_settings: ApiRequest<
      InternalPluginSettings,
      InternalPluginSettingsHydrated,
      InternalPluginSettingsHydratedTwice,
      InternalPluginSettings.FilterableFields
    >;

    _tag: ApiRequest<
      InternalTag,
      InternalTagHydrated,
      InternalTagHydratedTwice,
      InternalTag.FilterableFields
    >;

    _webhooks: ApiRequest<
      InternalWebhooks,
      InternalWebhooksHydrated,
      InternalWebhooksHydratedTwice,
      InternalWebhooks.FilterableFields
    >;
  }

  export interface FlotiqSearchAPI {
    query<P extends SearchParams>(
      params?: P,
    ): Promise<
      HydratedSearchResponse<
        P,
        AnySpaceCTD,
        AnySpaceCTDHydrated,
        AnySpaceCTDHydratedTwice
      >
    >;
  }
}
